/* ============================================================
   HAVENLY HOME DECOR — Datos de catálogo e idiomas
   ============================================================ */

const CATEGORIES = [
  { key: "sala",          icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M5 11V7a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v4"/><path d="M3 13a2 2 0 0 1 4 0v1h10v-1a2 2 0 0 1 4 0v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M5 18v2M19 18v2"/></svg>' },
  { key: "dormitorio",    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M2 9V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v4"/><path d="M2 9h20v5a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2z"/><path d="M6 16v4M18 16v4"/></svg>' },
  { key: "comedor",       icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 8h18"/><path d="M3 16h18"/><path d="M6 8v8M18 8v8"/><path d="M8 8V5M16 8V5"/></svg>' },
  { key: "cocina",        icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 10h16v4a6 6 0 0 1-6 6h-4a6 6 0 0 1-6-6z"/><path d="M8 10V6M16 10V6"/><path d="M8 3v2M16 3v2"/></svg>' },
  { key: "pared",         icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="1"/><path d="m8 16 3-4 2 2 2-3 3 5z"/></svg>' },
  { key: "iluminacion",   icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18h6M10 21h4"/><path d="M12 3a6 6 0 0 0-4 10.5c.8.7 1 1.5 1 2.5h6c0-1 .2-1.8 1-2.5A6 6 0 0 0 12 3z"/></svg>' },
  { key: "alfombras",     icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="6" width="18" height="12" rx="1"/><path d="M3 9.5h18M3 13h18M3 16.5h18"/></svg>' },
  { key: "accesorios",    icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3h8l1 7a5 5 0 0 1-10 0z"/><path d="M10 3c0 3 1 4 2 4s2-1 2-4"/></svg>' },
  { key: "almacenamiento",icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M5 8h14l-1 12H6z"/><path d="M4 8c0-2 2-3 4-3h8c2 0 4 1 4 3"/><path d="M9 8v5M15 8v5"/></svg>' },
  { key: "exterior",      icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21v-7"/><path d="M12 14c0-4 3-7 8-8-1 5-4 8-8 8z"/><path d="M12 14c0-3-2-5-6-6 0 4 2 6 6 6z"/></svg>' }
];

const PRODUCTS = [
  {
    id: "sofa-terracota",
    name: "Sofá Terracota Atemporal",
    nameEn: "Timeless Terracotta Sofa",
    category: "sala",
    price: 260,
    oldPrice: 520,
    rating: 4.9,
    reviews: 128,
    badge: "oferta",
    image: "assets/img/sofa-terracota.webp",
    gallery: ["assets/img/sofa-terracota.webp", "assets/img/cojin.jpg", "assets/img/alfombra.webp"],
    short: "Sofá de 3 puestos tapizado en lino color terracota con estructura de madera certificada.",
    shortEn: "3-seater sofa upholstered in terracotta linen with certified wood frame.",
    desc: "Un sofá que combina confort y elegancia. Tapizado en lino de alta resistencia, relleno de espuma de densidad premium y patas de madera de roble. Ideal para salas de estilo moderno y acogedor.",
    descEn: "A sofa that blends comfort and elegance. Upholstered in high-resistance linen, premium foam filling and oak wood legs. Perfect for modern, cozy living rooms.",
    stock: 12,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "cama-lino-oliva",
    name: "Cama Tapizada Verde Oliva",
    nameEn: "Olive Green Upholstered Bed",
    category: "dormitorio",
    price: 190,
    oldPrice: 380,
    rating: 4.8,
    reviews: 96,
    badge: "nuevo",
    image: "assets/img/dormitorio.png",
    gallery: ["assets/img/dormitorio.png", "assets/img/almacenamiento.jpg", "assets/img/lampara.jpg"],
    short: "Cabecero tapizado en terciopelo verde oliva, base de madera maciza.",
    shortEn: "Headboard upholstered in olive green velvet, solid wood base.",
    desc: "Dale a tu dormitorio un aire sereno con esta cama de cabecero alto tapizado en terciopelo verde oliva. Incluye base reforzada y soporte para colchón.",
    descEn: "Give your bedroom a serene feel with this high headboard bed upholstered in olive green velvet. Includes reinforced base and mattress support.",
    stock: 8,
    bestSeller: true,
    newArrival: true
  },
  {
    id: "comedor-roble",
    name: "Comedor Roble y Ratán",
    nameEn: "Oak & Rattan Dining Set",
    category: "comedor",
    price: 320,
    oldPrice: 640,
    rating: 4.7,
    reviews: 74,
    badge: "oferta",
    image: "assets/img/comedor.webp",
    gallery: ["assets/img/comedor.webp", "assets/img/silla.jpg", "assets/img/mesa.jpg"],
    short: "Mesa de roble con 4 sillas de ratán tejido a mano.",
    shortEn: "Oak table with 4 handwoven rattan chairs.",
    desc: "Conjunto de comedor artesanal: mesa de roble macizo y sillas de ratán natural tejidas a mano. Aporta calidez y estilo orgánico a tu comedor.",
    descEn: "Handcrafted dining set: solid oak table and natural handwoven rattan chairs. Brings warmth and organic style to your dining room.",
    stock: 6,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "set-cocina-ceramica",
    name: "Set Cocina Cerámica Artesanal",
    nameEn: "Handmade Ceramic Kitchen Set",
    category: "cocina",
    price: 48,
    oldPrice: 95,
    rating: 4.9,
    reviews: 210,
    badge: null,
    image: "assets/img/cocina.webp",
    gallery: ["assets/img/cocina.webp", "assets/img/jarron.jpg", "assets/img/accesorio.jpg"],
    short: "Vajilla de cerámica esmaltada en tonos tierra, hecha a mano.",
    shortEn: "Handmade glazed ceramic dinnerware in earthy tones.",
    desc: "Set de 12 piezas de cerámica esmaltada a mano. Cada pieza es única, con acabados en tonos arena y terracota. Apta para lavavajillas y microondas.",
    descEn: "12-piece handmade glazed ceramic set. Each piece is unique with sand and terracotta finishes. Dishwasher and microwave safe.",
    stock: 25,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "arte-pared-botanico",
    name: "Arte de Pared Botánico",
    nameEn: "Botanical Wall Art",
    category: "pared",
    price: 43,
    oldPrice: 85,
    rating: 4.6,
    reviews: 54,
    badge: "oferta",
    image: "assets/img/pared.webp",
    gallery: ["assets/img/pared.webp", "assets/img/cojin.jpg", "assets/img/jarron.jpg"],
    short: "Láminas botánicas enmarcadas en madera natural, set de 3.",
    shortEn: "Set of 3 botanical prints framed in natural wood.",
    desc: "Trío de láminas botánicas impresas en papel de algodón y enmarcadas en madera natural. Perfectas para decorar salas, pasillos y dormitorios.",
    descEn: "Trio of botanical prints on cotton paper framed in natural wood. Perfect for living rooms, hallways and bedrooms.",
    stock: 18,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "lampara-ratan",
    name: "Lámpara Colgante de Ratán",
    nameEn: "Rattan Pendant Lamp",
    category: "iluminacion",
    price: 55,
    oldPrice: 110,
    rating: 4.8,
    reviews: 88,
    badge: "nuevo",
    image: "assets/img/iluminacion.png",
    gallery: ["assets/img/iluminacion.png", "assets/img/lampara.jpg", "assets/img/comedor.webp"],
    short: "Lámpara colgante tejida a mano que filtra una luz cálida.",
    shortEn: "Handwoven pendant lamp that filters warm light.",
    desc: "Lámpara colgante de ratán tejida a mano. Crea un ambiente cálido y acogedor con su luz tamizada. Incluye cable de 1,5 m y casquillo E27.",
    descEn: "Handwoven rattan pendant lamp. Creates a warm, cozy atmosphere with its filtered light. Includes 1.5 m cord and E27 socket.",
    stock: 15,
    bestSeller: true,
    newArrival: true
  },
  {
    id: "alfombra-yute",
    name: "Alfombra de Yute Natural",
    nameEn: "Natural Jute Rug",
    category: "alfombras",
    price: 90,
    oldPrice: 180,
    rating: 4.7,
    reviews: 67,
    badge: "oferta",
    image: "assets/img/alfombra.webp",
    gallery: ["assets/img/alfombra.webp", "assets/img/sofa-terracota.webp", "assets/img/cojin.jpg"],
    short: "Alfombra tejida a mano en yute 100% natural, 160 x 230 cm.",
    shortEn: "Handwoven 100% natural jute rug, 160 x 230 cm.",
    desc: "Alfombra de yute tejida a mano, resistente y sostenible. Su textura natural aporta calidez a cualquier espacio. Ideal para salas y dormitorios.",
    descEn: "Handwoven jute rug, durable and sustainable. Its natural texture adds warmth to any space. Ideal for living rooms and bedrooms.",
    stock: 10,
    bestSeller: false,
    newArrival: true
  },
  {
    id: "jarron-ceramica",
    name: "Jarrón Cerámica Terracota",
    nameEn: "Terracotta Ceramic Vase",
    category: "accesorios",
    price: 23,
    oldPrice: 45,
    rating: 4.8,
    reviews: 142,
    badge: null,
    image: "assets/img/jarron.jpg",
    gallery: ["assets/img/jarron.jpg", "assets/img/accesorio.jpg", "assets/img/pared.webp"],
    short: "Jarrón decorativo de cerámica en tono terracota, hecho a mano.",
    shortEn: "Decorative handmade terracotta ceramic vase.",
    desc: "Jarrón de cerámica artesanal en tono terracota con acabado mate. Pieza única para decorar mesas, repisas o recibidores con flores secas o frescas.",
    descEn: "Handcrafted terracotta ceramic vase with matte finish. A unique piece to decorate tables, shelves or entryways with dried or fresh flowers.",
    stock: 30,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "cesta-almacenaje",
    name: "Cesta de Almacenaje Tejida",
    nameEn: "Woven Storage Basket",
    category: "almacenamiento",
    price: 24,
    oldPrice: 48,
    rating: 4.5,
    reviews: 59,
    badge: "oferta",
    image: "assets/img/almacenamiento.jpg",
    gallery: ["assets/img/almacenamiento.jpg", "assets/img/alfombra.webp", "assets/img/cocina.webp"],
    short: "Cesta de fibra natural con asas, ideal para organizar cualquier rincón.",
    shortEn: "Natural fiber basket with handles, ideal to organize any corner.",
    desc: "Cesta de almacenaje tejida a mano en fibra natural con asas reforzadas. Perfecta para mantas, juguetes, ropa o plantas. Disponible en varios tamaños.",
    descEn: "Handwoven storage basket in natural fiber with reinforced handles. Perfect for blankets, toys, clothes or plants. Available in several sizes.",
    stock: 22,
    bestSeller: false,
    newArrival: true
  },
  {
    id: "silla-rattan",
    name: "Silla Colgante de Ratán",
    nameEn: "Rattan Hanging Chair",
    category: "exterior",
    price: 130,
    oldPrice: 260,
    rating: 4.9,
    reviews: 73,
    badge: "nuevo",
    image: "assets/img/exterior.jpg",
    gallery: ["assets/img/exterior.jpg", "assets/img/silla.jpg", "assets/img/comedor.webp"],
    short: "Silla colgante de ratán con cojín, para interiores y exteriores.",
    shortEn: "Rattan hanging chair with cushion, for indoor and outdoor use.",
    desc: "Silla colgante de ratán sintético resistente a la intemperie, con cojín lavable. Añade un rincón de relax a tu terraza, jardín o sala de estar.",
    descEn: "Weather-resistant synthetic rattan hanging chair with washable cushion. Adds a relaxing corner to your terrace, garden or living room.",
    stock: 7,
    bestSeller: false,
    newArrival: true
  },
  {
    id: "silla-comedor-oliva",
    name: "Silla Comedor Verde Oliva",
    nameEn: "Olive Green Dining Chair",
    category: "comedor",
    price: 75,
    oldPrice: 150,
    rating: 4.6,
    reviews: 41,
    badge: "oferta",
    image: "assets/img/silla.jpg",
    gallery: ["assets/img/silla.jpg", "assets/img/comedor.webp", "assets/img/mesa.jpg"],
    short: "Silla tapizada en tela verde oliva con patas de madera.",
    shortEn: "Chair upholstered in olive green fabric with wooden legs.",
    desc: "Silla de comedor con asiento y respaldo tapizados en tela verde oliva, patas de madera de haya. Cómoda, elegante y fácil de combinar.",
    descEn: "Dining chair with seat and back upholstered in olive green fabric, beech wood legs. Comfortable, elegant and easy to match.",
    stock: 14,
    bestSeller: false,
    newArrival: false
  },
  {
    id: "lampara-mesa-ceramica",
    name: "Lámpara de Mesa Cerámica",
    nameEn: "Ceramic Table Lamp",
    category: "iluminacion",
    price: 43,
    oldPrice: 85,
    rating: 4.7,
    reviews: 62,
    badge: null,
    image: "assets/img/lampara.jpg",
    gallery: ["assets/img/lampara.jpg", "assets/img/iluminacion.png", "assets/img/dormitorio.png"],
    short: "Lámpara de mesa con base de cerámica beige y pantalla de lino.",
    shortEn: "Table lamp with beige ceramic base and linen shade.",
    desc: "Lámpara de mesa con base de cerámica en tono beige y pantalla de lino natural. Luz cálida ideal para mesas de noche y salas de lectura.",
    descEn: "Table lamp with beige ceramic base and natural linen shade. Warm light ideal for nightstands and reading corners.",
    stock: 16,
    bestSeller: true,
    newArrival: false
  },
  {
    id: "cojin-lino",
    name: "Cojín Lino Terracota",
    nameEn: "Terracotta Linen Cushion",
    category: "sala",
    price: 16,
    oldPrice: 32,
    rating: 4.8,
    reviews: 95,
    badge: null,
    image: "assets/img/cojin.jpg",
    gallery: ["assets/img/cojin.jpg", "assets/img/sofa-terracota.webp", "assets/img/alfombra.webp"],
    short: "Cojín decorativo de lino con relleno de fibra hipoalergénica.",
    shortEn: "Decorative linen cushion with hypoallergenic fiber filling.",
    desc: "Cojín decorativo de lino en tono terracota con cierre invisible y relleno de fibra hipoalergénica. Suave al tacto y fácil de lavar.",
    descEn: "Decorative terracotta linen cushion with invisible zipper and hypoallergenic fiber filling. Soft to the touch and easy to wash.",
    stock: 40,
    bestSeller: false,
    newArrival: true
  },
  {
    id: "mesa-centro-roble",
    name: "Mesa de Centro Roble",
    nameEn: "Oak Coffee Table",
    category: "sala",
    price: 115,
    oldPrice: 230,
    rating: 4.6,
    reviews: 38,
    badge: "oferta",
    image: "assets/img/mesa.jpg",
    gallery: ["assets/img/mesa.jpg", "assets/img/comedor.webp", "assets/img/sofa-terracota.webp"],
    short: "Mesa de centro de roble macizo con acabado natural.",
    shortEn: "Solid oak coffee table with natural finish.",
    desc: "Mesa de centro de roble macizo con acabado en aceite natural. Superficie amplia y líneas minimalistas que realzan cualquier sala.",
    descEn: "Solid oak coffee table with natural oil finish. Wide surface and minimalist lines that enhance any living room.",
    stock: 9,
    bestSeller: false,
    newArrival: false
  },
  {
    id: "espejo-ratan",
    name: "Espejo Redondo de Ratán",
    nameEn: "Round Rattan Mirror",
    category: "pared",
    price: 49,
    oldPrice: 98,
    rating: 4.7,
    reviews: 51,
    badge: "nuevo",
    image: "assets/img/accesorio.jpg",
    gallery: ["assets/img/accesorio.jpg", "assets/img/pared.webp", "assets/img/jarron.jpg"],
    short: "Espejo redondo con marco de ratán tejido a mano.",
    shortEn: "Round mirror with handwoven rattan frame.",
    desc: "Espejo redondo con marco de ratán tejido a mano. Aporta amplitud y un toque boho-natural a cualquier pared de tu hogar.",
    descEn: "Round mirror with handwoven rattan frame. Adds spaciousness and a boho-natural touch to any wall in your home.",
    stock: 13,
    bestSeller: false,
    newArrival: true
  },
  {
    id: "maceta-terracota",
    name: "Maceta Terracota con Plato",
    nameEn: "Terracotta Pot with Saucer",
    category: "exterior",
    price: 15,
    oldPrice: 30,
    rating: 4.5,
    reviews: 77,
    badge: "oferta",
    image: "assets/img/accesorio.jpg",
    gallery: ["assets/img/accesorio.jpg", "assets/img/exterior.jpg", "assets/img/jarron.jpg"],
    short: "Maceta de barro cocido con plato, ideal para interiores y exteriores.",
    shortEn: "Fired clay pot with saucer, ideal for indoor and outdoor use.",
    desc: "Maceta de barro cocido en tono terracota con plato incluido. Material poroso que favorece la salud de tus plantas. Resistente a la intemperie.",
    descEn: "Fired terracotta clay pot with included saucer. Porous material that promotes plant health. Weather resistant.",
    stock: 0,
    bestSeller: false,
    newArrival: false
  }
];

const TESTIMONIALS = [
  {
    name: "María Fernanda R.",
    location: "Caracas, Venezuela",
    rating: 5,
    text: "La calidad de los productos superó mis expectativas. El sofá terracota transformó mi sala por completo. ¡El envío llegó rapidísimo!",
    textEn: "The product quality exceeded my expectations. The terracotta sofa completely transformed my living room. Shipping was super fast!",
    initials: "MR"
  },
  {
    name: "Carlos E. Pérez",
    location: "Valencia, Venezuela",
    rating: 5,
    text: "Compré la lámpara de ratán y el set de cerámica. Todo llegó perfectamente empacado. El pago con Binance Pay fue súper fácil.",
    textEn: "I bought the rattan lamp and the ceramic set. Everything arrived perfectly packed. Paying with Binance Pay was super easy.",
    initials: "CP"
  },
  {
    name: "Andrea G. López",
    location: "Maracaibo, Venezuela",
    rating: 4,
    text: "Me encanta la estética de la tienda. Los cojines y la alfombra de yute le dieron a mi apartamento un aire acogedor y elegante.",
    textEn: "I love the store's aesthetic. The cushions and jute rug gave my apartment a cozy and elegant feel.",
    initials: "AL"
  },
  {
    name: "Luis A. Mendoza",
    location: "Barquisimeto, Venezuela",
    rating: 5,
    text: "Excelente atención al cliente por WhatsApp. Me ayudaron a elegir la mesa de centro perfecta para mi sala. 100% recomendados.",
    textEn: "Excellent customer service via WhatsApp. They helped me choose the perfect coffee table for my living room. 100% recommended.",
    initials: "LM"
  }
];

const I18N = {
  es: {
    "topbar.ship": "Envíos gratis en pedidos mayores a $75",
    "topbar.discount": "15% de descuento en tu primera compra | Código: BIENVENIDO15",
    "topbar.returns": "Devoluciones fáciles hasta 30 días",
    "nav.home": "INICIO",
    "nav.shop": "TIENDA",
    "nav.rooms": "AMBIENTES",
    "nav.collections": "COLECCIONES",
    "nav.news": "NOVEDADES",
    "nav.offers": "OFERTAS",
    "nav.about": "NOSOTROS",
    "search.placeholder": "Buscar productos...",
    "hero.title": "Hogar Hermoso. Mejor Vida.",
    "hero.subtitle": "Decoración atemporal. Diseño con propósito. Piezas que hacen que tu casa se sienta como hogar.",
    "hero.cta1": "COMPRAR AHORA",
    "hero.cta2": "EXPLORAR COLECCIONES",
    "hero.b1": "Calidad Premium",
    "hero.b2": "Materiales Sostenibles",
    "hero.b3": "Pago 100% Seguro",
    "hero.b4": "Soporte Experto",
    "offer.text": "¡Disfruta 15% OFF en tu primer pedido! | Usa el código:",
    "offer.cta": "RECLAMAR OFERTA",
    "shop.title": "Compra por Categoría",
    "shop.subtitle": "Encuentra piezas únicas para cada rincón de tu hogar",
    "best.title": "Más Vendidos",
    "best.subtitle": "Los favoritos de nuestros clientes",
    "new.title": "Novedades",
    "new.subtitle": "Recién llegados a la colección",
    "product.add": "AÑADIR AL CARRITO",
    "product.added": "Añadido al carrito",
    "product.view": "Ver producto",
    "badge.new": "NUEVO",
    "badge.sale": "OFERTA",
    "banner1.title": "Estilo Atemporal",
    "banner1.subtitle": "Neutros terrosos que nunca pasan de moda",
    "banner1.cta": "Explorar colección",
    "banner2.title": "Renueva tu espacio",
    "banner2.subtitle": "Novedades de primavera para tu hogar",
    "banner2.cta": "Comprar novedades",
    "testi.title": "Lo que dicen nuestros clientes",
    "testi.subtitle": "Historias reales de hogares felices",
    "trust.free": "Envíos gratis",
    "trust.free.d": "En pedidos mayores a $75",
    "trust.returns": "Devoluciones 30 días",
    "trust.returns.d": "Sin complicaciones",
    "trust.pay": "Pagos seguros",
    "trust.pay.d": "Múltiples métodos",
    "trust.support": "Soporte top",
    "trust.support.d": "Atención personalizada",
    "footer.desc": "Decoración atemporal y piezas con propósito para hacer de tu casa un verdadero hogar.",
    "footer.shop": "TIENDA",
    "footer.help": "AYUDA",
    "footer.about": "NOSOTROS",
    "footer.news": "Suscríbete a nuestro newsletter",
    "footer.news.d": "Recibe ofertas exclusivas y novedades en tu correo.",
    "footer.email": "Tu correo electrónico",
    "footer.subscribe": "SUSCRIBIRSE",
    "footer.rights": "Todos los derechos reservados.",
    "cart.title": "Tu Carrito",
    "cart.empty": "Tu carrito está vacío",
    "cart.empty.d": "Descubre nuestras piezas favoritas y empieza a decorar tu hogar.",
    "cart.continue": "Seguir comprando",
    "cart.product": "Producto",
    "cart.price": "Precio",
    "cart.qty": "Cantidad",
    "cart.total": "Total",
    "cart.remove": "Eliminar",
    "cart.summary": "Resumen del pedido",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Envío",
    "cart.tax": "Impuestos (16%)",
    "cart.grand": "Total",
    "cart.free": "Gratis",
    "cart.checkout": "IR AL PAGO",
    "cart.promo": "¿Tienes un código de descuento?",
    "cart.apply": "Aplicar",
    "cart.code.ok": "Código aplicado: 15% de descuento",
    "cart.code.bad": "Código inválido",
    "checkout.title": "Finalizar Compra",
    "checkout.personal": "Datos personales",
    "checkout.name": "Nombre completo",
    "checkout.email": "Correo electrónico",
    "checkout.phone": "Teléfono",
    "checkout.shipping": "Dirección de envío",
    "checkout.address": "Dirección",
    "checkout.city": "Ciudad",
    "checkout.state": "Estado",
    "checkout.zip": "Código postal",
    "checkout.payment": "Método de pago",
    "checkout.pay.desc": "Selecciona cómo deseas pagar",
    "checkout.card": "Tarjeta de crédito / débito",
    "checkout.card.d": "Visa, Mastercard, American Express (Stripe)",
    "checkout.mp": "Mercado Pago",
    "checkout.mp.d": "Paga con saldo, tarjeta o efectivo",
    "checkout.pp": "PayPal",
    "checkout.pp.d": "Pago internacional seguro",
    "checkout.binance": "Binance Pay",
    "checkout.binance.d": "Pago con criptomonedas (USDT)",
    "checkout.zelle": "Zelle",
    "checkout.zelle.d": "Transferencia bancaria internacional",
    "checkout.transfer": "Transferencia bancaria (Bs)",
    "checkout.transfer.d": "Pago móvil en bolívares",
    "checkout.place": "CONFIRMAR PEDIDO",
    "checkout.note": "Al confirmar aceptas nuestros términos y condiciones.",
    "checkout.required": "Por favor completa todos los campos obligatorios.",
    "success.title": "¡Pedido confirmado!",
    "success.sub": "Gracias por tu compra. Te enviamos un correo con los detalles de tu pedido.",
    "success.order": "Número de pedido",
    "success.email": "Enviaremos la confirmación a",
    "success.back": "Volver a la tienda",
    "wa.msg": "¡Hola! Me interesan los productos de HAVENLY HOME DECOR. ¿Me pueden ayudar?",
    "detail.desc": "Descripción",
    "detail.reviews": "Reseñas",
    "detail.qty": "Cantidad",
    "detail.stock": "Disponibles",
    "detail.sku": "SKU",
    "detail.category": "Categoría",
    "detail.buy": "COMPRAR AHORA",
    "detail.related": "También te puede gustar",
    "filter.title": "Filtrar productos",
    "filter.category": "Categoría",
    "filter.all": "Todas",
    "filter.price": "Precio",
    "filter.avail": "Disponibilidad",
    "filter.in": "En stock",
    "filter.out": "Agotado",
    "filter.clear": "Limpiar filtros",
    "filter.results": "productos",
    "filter.noresults": "No se encontraron productos con esos filtros.",
    "sort.featured": "Destacados",
    "sort.priceAsc": "Precio: menor a mayor",
    "sort.priceDesc": "Precio: mayor a menor",
    "sort.rating": "Mejor valorados",
    "lang.es": "ES",
    "lang.en": "EN",
    "cart.count": "artículos"
  },
  en: {
    "topbar.ship": "Free shipping on orders over $75",
    "topbar.discount": "15% off your first purchase | Code: BIENVENIDO15",
    "topbar.returns": "Easy returns up to 30 days",
    "nav.home": "HOME",
    "nav.shop": "SHOP",
    "nav.rooms": "ROOMS",
    "nav.collections": "COLLECTIONS",
    "nav.news": "NEW IN",
    "nav.offers": "SALE",
    "nav.about": "ABOUT",
    "search.placeholder": "Search products...",
    "hero.title": "Beautiful Home. Better Life.",
    "hero.subtitle": "Timeless decor. Purposeful design. Pieces that make your house feel like home.",
    "hero.cta1": "SHOP NOW",
    "hero.cta2": "EXPLORE COLLECTIONS",
    "hero.b1": "Premium Quality",
    "hero.b2": "Sustainable Materials",
    "hero.b3": "100% Secure Payment",
    "hero.b4": "Expert Support",
    "offer.text": "Enjoy 15% OFF on your first order! | Use code:",
    "offer.cta": "CLAIM OFFER",
    "shop.title": "Shop by Category",
    "shop.subtitle": "Find unique pieces for every corner of your home",
    "best.title": "Best Sellers",
    "best.subtitle": "Our customers' favorites",
    "new.title": "New Arrivals",
    "new.subtitle": "Fresh in the collection",
    "product.add": "ADD TO CART",
    "product.added": "Added to cart",
    "product.view": "View product",
    "badge.new": "NEW",
    "badge.sale": "SALE",
    "banner1.title": "Timeless Style",
    "banner1.subtitle": "Earthy neutrals that never go out of style",
    "banner1.cta": "Explore collection",
    "banner2.title": "Refresh your space",
    "banner2.subtitle": "Spring new arrivals for your home",
    "banner2.cta": "Shop new arrivals",
    "testi.title": "What our customers say",
    "testi.subtitle": "Real stories from happy homes",
    "trust.free": "Free shipping",
    "trust.free.d": "On orders over $75",
    "trust.returns": "30-day returns",
    "trust.returns.d": "Hassle-free",
    "trust.pay": "Secure payments",
    "trust.pay.d": "Multiple methods",
    "trust.support": "Top support",
    "trust.support.d": "Personal attention",
    "footer.desc": "Timeless decor and purposeful pieces to make your house a true home.",
    "footer.shop": "SHOP",
    "footer.help": "HELP",
    "footer.about": "ABOUT",
    "footer.news": "Subscribe to our newsletter",
    "footer.news.d": "Get exclusive offers and news in your inbox.",
    "footer.email": "Your email address",
    "footer.subscribe": "SUBSCRIBE",
    "footer.rights": "All rights reserved.",
    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty.d": "Discover our favorite pieces and start decorating your home.",
    "cart.continue": "Continue shopping",
    "cart.product": "Product",
    "cart.price": "Price",
    "cart.qty": "Quantity",
    "cart.total": "Total",
    "cart.remove": "Remove",
    "cart.summary": "Order summary",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.tax": "Tax (16%)",
    "cart.grand": "Total",
    "cart.free": "Free",
    "cart.checkout": "CHECKOUT",
    "cart.promo": "Have a discount code?",
    "cart.apply": "Apply",
    "cart.code.ok": "Code applied: 15% off",
    "cart.code.bad": "Invalid code",
    "checkout.title": "Checkout",
    "checkout.personal": "Personal details",
    "checkout.name": "Full name",
    "checkout.email": "Email address",
    "checkout.phone": "Phone",
    "checkout.shipping": "Shipping address",
    "checkout.address": "Address",
    "checkout.city": "City",
    "checkout.state": "State",
    "checkout.zip": "ZIP code",
    "checkout.payment": "Payment method",
    "checkout.pay.desc": "Choose how you want to pay",
    "checkout.card": "Credit / debit card",
    "checkout.card.d": "Visa, Mastercard, American Express (Stripe)",
    "checkout.mp": "Mercado Pago",
    "checkout.mp.d": "Pay with balance, card or cash",
    "checkout.pp": "PayPal",
    "checkout.pp.d": "Secure international payment",
    "checkout.binance": "Binance Pay",
    "checkout.binance.d": "Pay with crypto (USDT)",
    "checkout.zelle": "Zelle",
    "checkout.zelle.d": "International bank transfer",
    "checkout.transfer": "Bank transfer (Bs)",
    "checkout.transfer.d": "Mobile payment in bolivars",
    "checkout.place": "PLACE ORDER",
    "checkout.note": "By confirming you accept our terms and conditions.",
    "checkout.required": "Please complete all required fields.",
    "success.title": "Order confirmed!",
    "success.sub": "Thank you for your purchase. We sent you an email with your order details.",
    "success.order": "Order number",
    "success.email": "We'll send confirmation to",
    "success.back": "Back to shop",
    "wa.msg": "Hello! I'm interested in HAVENLY HOME DECOR products. Can you help me?",
    "detail.desc": "Description",
    "detail.reviews": "Reviews",
    "detail.qty": "Quantity",
    "detail.stock": "In stock",
    "detail.sku": "SKU",
    "detail.category": "Category",
    "detail.buy": "BUY NOW",
    "detail.related": "You may also like",
    "filter.title": "Filter products",
    "filter.category": "Category",
    "filter.all": "All",
    "filter.price": "Price",
    "filter.avail": "Availability",
    "filter.in": "In stock",
    "filter.out": "Out of stock",
    "filter.clear": "Clear filters",
    "filter.results": "products",
    "filter.noresults": "No products found with those filters.",
    "sort.featured": "Featured",
    "sort.priceAsc": "Price: low to high",
    "sort.priceDesc": "Price: high to low",
    "sort.rating": "Top rated",
    "lang.es": "ES",
    "lang.en": "EN",
    "cart.count": "items"
  }
};
